ALTER TABLE users ADD COLUMN email_notify_applications BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN email_notify_scholarships BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN email_notify_system BOOLEAN NOT NULL DEFAULT TRUE;
