package com.scholarzim;

import com.scholarzim.support.MvcIntegrationTestBase;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * A missing static file must report 404, not 500.
 *
 * These paths previously fell through to the catch-all Exception handler, so every
 * broken asset link looked like a server fault — misleading monitoring, and telling
 * crawlers and CDNs the server was down rather than the URL wrong.
 */
class StaticResourceNotFoundMvcTest extends MvcIntegrationTestBase {

    @ParameterizedTest
    @ValueSource(strings = {
            "/css/does-not-exist.css",
            "/js/does-not-exist.js",
            "/images/does-not-exist.png",
            "/icons/does-not-exist.svg",
            "/app/assets/does-not-exist.js",
    })
    void missingStaticResourceReturnsNotFound(String path) throws Exception {
        mockMvc.perform(get(path)).andExpect(status().isNotFound());
    }

    /**
     * The SPA shell is generated by the frontend build and is absent from a
     * backend-only checkout, so this asserts the graceful case: /app 404s rather
     * than throwing, leaving the Thymeleaf pages untouched.
     */
    @Test
    void bareAppPathDoesNotServerError() throws Exception {
        mockMvc.perform(get("/app"))
                .andExpect(result -> {
                    int status = result.getResponse().getStatus();
                    if (status >= 500) {
                        throw new AssertionError("/app returned " + status + ", expected 200 or 404");
                    }
                });
    }
}
