<?php

namespace App\Support;

use App\Http\Controllers\SourceAssetController;

/**
 * Everything the installable-app layer needs to describe itself: the manifest,
 * the list of files worth holding on a device, and the one version string that
 * makes a deploy replace them.
 *
 * It lives in Support rather than in the controller because three callers need
 * the same answers - the manifest route, the service-worker route, and the tests
 * - and because the precache list has to be derived from the *current* build
 * rather than written down. ScholarZim's own CSS and JS are content-hashed by
 * Vite and their filenames change every build, so a hand-maintained list would
 * be wrong the first time anyone ran `npm run build`.
 *
 * Nothing here knows a hostname. Every URL is built with url()/asset(), so the
 * same code serves http://localhost:8001 in development and whatever APP_URL is
 * in production without a branch.
 */
final class Pwa
{
    /**
     * The theme colour, taken from the BVite theme the layouts actually select:
     * `data-bvite="theme-Mariner"` sets --primary-color to this. It paints the
     * Android status bar and the splash screen, so a value invented here would
     * show up as a seam around the real UI.
     */
    public const THEME_COLOR = '#0066FE';

    /**
     * The splash background. Deliberately the light body background rather than
     * the theme colour: the splash is shown for a moment before the page paints,
     * and matching the page it precedes is what stops the launch from flashing.
     */
    public const BACKGROUND_COLOR = '#ffffff';

    /** Icons, as they appear in the manifest. Regenerated by scholarzim:pwa-icons. */
    private const ICONS = [
        ['assets/img/icon-192.png', '192x192', 'any'],
        ['assets/img/icon-512.png', '512x512', 'any'],
        ['assets/img/icon-maskable-512.png', '512x512', 'maskable'],
    ];

    /**
     * Static files that are the same for every visitor, signed in or not.
     *
     * This list is the whole of what a device is allowed to keep. It is an
     * explicit allow-list rather than a rule the service worker evaluates at
     * runtime, because "cache what looks static" is exactly the reasoning that
     * ends with somebody's application history on a shared phone.
     */
    private const STATIC_ASSETS = [
        'assets/bvite/css/bvite-base.css',
        'assets/bvite/css/bvite-theme.css',
        'assets/bvite/js/bvite.js',
        'assets/js/theme-toggle.js',
        'assets/img/favicon.ico',
        'assets/img/icon-192.png',
        'assets/img/icon-512.png',
        'assets/img/icon-maskable-512.png',
        'assets/img/apple-touch-icon.png',
    ];

    private function __construct()
    {
    }

    /**
     * The web app manifest, as an array ready to be encoded.
     *
     * `start_url` and `scope` are the site root: ScholarZim decides where a
     * visitor belongs from their role and their session, so the installed app
     * opens at "/" and is redirected the same way a bookmark would be. Pinning
     * it at a dashboard would open a signed-out launcher on a login redirect,
     * and pin the wrong dashboard for two of the three roles.
     *
     * @return array<string, mixed>
     */
    public static function manifest(): array
    {
        return [
            'name' => 'ScholarZim',
            'short_name' => 'ScholarZim',
            'description' => 'Centralized scholarship discovery and application platform for students and verified scholarship providers.',
            'id' => '/',
            'start_url' => '/',
            'scope' => '/',
            'display' => 'standalone',
            'orientation' => 'portrait-primary',
            'theme_color' => self::THEME_COLOR,
            'background_color' => self::BACKGROUND_COLOR,
            'lang' => 'en',
            'dir' => 'ltr',
            'categories' => ['education'],
            'icons' => array_map(fn (array $icon) => [
                'src' => asset($icon[0]),
                'sizes' => $icon[1],
                'type' => 'image/png',
                'purpose' => $icon[2],
            ], self::ICONS),
        ];
    }

    /**
     * The URLs the service worker precaches on install.
     *
     * The offline page comes first because it is the one entry whose absence is
     * visible: without it a lost connection shows the browser's own error page
     * instead of ScholarZim's.
     *
     * @return list<string>
     */
    public static function precacheUrls(): array
    {
        $urls = [url('/offline')];

        foreach (self::STATIC_ASSETS as $path) {
            if (is_file(public_path($path))) {
                $urls[] = asset($path);
            }
        }

        foreach (self::appAssetPaths() as $path) {
            $urls[] = $path;
        }

        return array_values(array_unique($urls));
    }

    /**
     * ScholarZim's own CSS and JS, however they are currently being delivered.
     *
     * Reads the Vite manifest for the hashed filenames when a build is present,
     * and falls back to the same source-file URLs partials/assets.blade.php uses
     * when it is not - so the precache matches what the pages actually request
     * either way, rather than caching a build that is not being served.
     *
     * @return list<string>
     */
    public static function appAssetPaths(): array
    {
        if (! FrontendAssets::viteReady()) {
            $urls = [route('assets.source', 'scholarzim.css')];

            foreach (SourceAssetController::FALLBACK_SCRIPTS as $script) {
                $urls[] = route('assets.source', $script);
            }

            return $urls;
        }

        $manifestPath = public_path('build/manifest.json');
        $manifest = json_decode((string) @file_get_contents($manifestPath), true);

        if (! is_array($manifest)) {
            return [];
        }

        $urls = [];

        foreach (['resources/css/app.css', 'resources/js/app.js'] as $entry) {
            $file = $manifest[$entry]['file'] ?? null;

            if (is_string($file)) {
                $urls[] = asset('build/' . $file);
            }

            foreach ((array) ($manifest[$entry]['css'] ?? []) as $stylesheet) {
                $urls[] = asset('build/' . $stylesheet);
            }
        }

        return $urls;
    }

    /**
     * A version string that changes whenever anything cached would change.
     *
     * This is the whole of the cache-invalidation strategy, and it is derived
     * rather than declared for the reason every hand-bumped version eventually
     * fails: the bump is a separate action from the change, so it gets missed,
     * and an installed app keeps serving the previous deploy's stylesheet with
     * no error anywhere to say why.
     *
     * Three things feed it: the service-worker source (so a change to the
     * caching rules ships), and the precache URLs plus the content of any of
     * them that is not already content-hashed (so a rebuilt bundle ships, and so
     * does an edit to the un-hashed fallback assets).
     */
    public static function cacheVersion(): string
    {
        static $version;

        if ($version !== null) {
            return $version;
        }

        $parts = [(string) @md5_file(self::serviceWorkerSourcePath())];

        foreach (self::precacheUrls() as $url) {
            $parts[] = $url;

            $relative = ltrim((string) parse_url($url, PHP_URL_PATH), '/');
            $file = public_path($relative);

            // Vite's output is content-hashed, so its URL already is its
            // fingerprint. Everything else has a stable URL and mutable
            // contents, and has to be hashed to be noticed.
            if (! str_starts_with($relative, 'build/') && is_file($file)) {
                $parts[] = (string) @md5_file($file);
            }
        }

        return $version = substr(md5(implode('|', $parts)), 0, 12);
    }

    public static function serviceWorkerSourcePath(): string
    {
        return resource_path('pwa/service-worker.js');
    }
}
